### ISSUE TITLE
Be sure the collection is tested against 2.11

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/frr.frr#33]
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

I was going to copy sanity/ignore-2.11.txt to sanity/ignore-2.12.txt but there are only ignore-2.10.txt.
If everything is OK and is under control, feel free to close the issue

##### ISSUE TYPE
- Feature Idea

**Comment by NilashishC** [comment]
Closing since https://github.com/ansible/ansible-zuul-jobs/pull/882 is now merged.

**Comment by Andersson007** [comment]
@NilashishC great, thanks! So since now all the collections that tested by Zuul are tested against 2.11, right?
