### ISSUE TITLE
Removal from Ansible Community Package

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/frr.frr#68]
There has been an announcement deprecating this collection in [The Bullhorn #123](https://forum.ansible.com/t/2568). It says there won't be any more major releases, but I don't see any minor or even bugfix releases either for quite some time.

This repo isn't archived and there is no information about deprecation neither in the repo nor on [galaxy](https://galaxy.ansible.com/ui/repo/published/frr/frr/). However, because of the deprecation announcement there is now a discussion about [removing this collecection from the Ansible Community Package](https://forum.ansible.com/t/6243).

At least one month after this announcement appears here and on [Bullhorn](https://forum.ansible.com/c/news/bullhorn/17), the Ansible Community Steering Committee will vote on whether this collection will be removed, or whether it will be kept. If it will be removed, this will happen earliest in Ansible 11. Please note that people can still manually install the collection with `ansible-galaxy collection install frr.frr` even when it has been removed from Ansible.

**Comment by NilashishC** [comment]
Hello @mariolenz! I’m from the Ansible Network team, that maintains the frr.frr collection. This collection was deprecated in December, 2023 and will reach end-of-life on December, 2025. During this period, we will only be doing patch releases for this collection if a critical bug or security vulnerability has been reported.

We will continue to run ansible-test in CI for ansible-core<=2.17, >=2.15 and as such compatibility with ansible-core versions >2.17 will not be guaranteed.

I have opened a PR that fixes the sanity failure with >=stable-2.16 and also an update to the README mentioning all the above. (Apologies to the Community for not doing that along with the Bullhorn announcement.)

Please let me know if the above points would qualify this collection to continue being included in the Ansible Community Package.

Thank you!

**Comment by mariolenz** [comment]
Thanks @NilashishC! This is a very important and valuable information:

> This collection was deprecated in December, 2023 and will reach end-of-life on December, 2025. During this period, we will only be doing patch releases for this collection if a critical bug or security vulnerability has been reported.

This sounds like we shouldn't remove the collection ASAP / from Ansible 11. But also that we might want to announce the deprecation / removal from a future version of the Ansible Community Package. If we keep releasing new Ansible versions as we did in the past, I think 13 would have an ETA of around November 2025 and would be a good time.

**Comment by mariolenz** [comment]
FYI: ansible-community/ansible-build-data#437
